### ISSUE TITLE
Invalid LIApplication object error 60021

### ISSUE THREAD

**Issue by hemang-ega** [vijayviswas/LIExplorer#3]
I am getting following error while trying initialize the `LIApplication` object. There's no information provided on this code. **Can you tell me what's going wrong?**

This is what I am doing right now to share my content on LinkedIn.

```
if(![LITokenHandler isValidToken])
{
    LIAuthorizationVC *vc = [[LIAuthorizationVC alloc] initWithSuccessBlock:^{
        [self dismissViewControllerAnimated:YES completion:nil];
        [LIRestAPIHandlers shareComment:@"" withTitle:@"My iPhone App" withDescription:@"" withSubmittedUrl:nil withImageURL:@"" withVisibity:LICommentVisibilityConnectionsOnly withCompletionBlock:^(NSDictionary *dic, NSURLResponse *response) {
            NSLog(@"%@",dic);
        } failure:^(NSError *error) {
            
        }];
    } failureBlock:^(NSError *error) {
        //That error is takign me in this block.
        NSDictionary *userInfo = [error userInfo];
        if([userInfo objectForKey:@"Url"])
        {
            NSLog(@"%@",error);
            NSLog(@"User clicked on link :%@",[userInfo objectForKey:@"Url"]);
        }
    }];
    [self.navigationController pushViewController:vc animated:YES];
} else {
    [LIRestAPIHandlers shareComment:@"My App." withTitle:@"My iPhone App" withDescription:@"" withSubmittedUrl:nil withImageURL:nil withVisibity:LICommentVisibilityConnectionsOnly withCompletionBlock:^(NSDictionary *dic, NSURLResponse *response) {
        NSLog(@"%@",dic);
    } failure:^(NSError *error) {
        NSLog(@"%@",error);
    }];
}
```

**Comment by vijayviswas** [comment]
I am on vacation now . Will look into this issue after Dec 5th

On Nov 19, 2016 2:59 PM, "hemang-ega" notifications@github.com wrote:

I am getting following error while trying initialize the LIApplication
object. There's no information provided on this code. _Can you tell me
what's going wrong?_

This is what I am doing right now to share my content on LinkedIn.

if(![LITokenHandler isValidToken])
{
    LIAuthorizationVC *vc = [[LIAuthorizationVC alloc] initWithSuccessBlock:^{
        [self dismissViewControllerAnimated:YES completion:nil];
        [LIRestAPIHandlers shareComment:@"" withTitle:@"My iPhone App"
withDescription:@"" withSubmittedUrl:nil withImageURL:@""
withVisibity:LICommentVisibilityConnectionsOnly
withCompletionBlock:^(NSDictionary *dic, NSURLResponse *response) {
            NSLog(@"%@",dic);
        } failure:^(NSError *error) {

```
    }];
} failureBlock:^(NSError *error) {
    //That error is takign me in this block.
    NSDictionary *userInfo = [error userInfo];
    if([userInfo objectForKey:@"Url"])
    {
        NSLog(@"%@",error);
        NSLog(@"User clicked on link :%@",[userInfo objectForKey:@"Url"]);
    }
}];
[self.navigationController pushViewController:vc animated:YES];
```

} else {
    [LIRestAPIHandlers shareComment:@"My App." withTitle:@"My iPhone
App" withDescription:@"" withSubmittedUrl:nil withImageURL:nil
withVisibity:LICommentVisibilityConnectionsOnly
withCompletionBlock:^(NSDictionary *dic, NSURLResponse *response) {
        NSLog(@"%@",dic);
    } failure:^(NSError *error) {
        NSLog(@"%@",error);
    }];
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/vijayviswas/LIExplorer/issues/3, or mute the thread

**Comment by vijayviswas** [comment]
@hemang-ega - Have you resolved the issue ?
